### ISSUE TITLE
Deployment to heroku

### ISSUE THREAD

**Issue by jaffamonkey** [InkhornGames/angular-blog#9]
Not so much an issue, a query - the code works locally no problem, but I am having devil of a job deploying to heroku.  This is partly due to my learning curve of angular (no doubt!).  Would appreciate a nudge in right direction :)

**Comment by austinkettner** [comment]
Hey @jaffamonkey,

To deploy to heroku you basdically would want to run `grunt` followed by `grunt buildcontrol:heroku` which will go about deploying the `/dist` folder. It will fail the first time, just go to the dist folder, and set the git remote origin url, then go back to root and run `grunt buildcontrol:heroku` once again.

Let me know if you have continued issues, happy to write up a more robust explanation!

**Comment by jaffamonkey** [comment]
Thanks for that, I got a lot further :) (https://calm-refuge-6204.herokuapp.com).  But now at error to do with "relativeDate" module.  
First part of error:- "Error: Cannot find module 'function (){angular.module("relativeDate",[]).".  It is loaded as far as I can tell. Feels close!

**Comment by austinkettner** [comment]
@jaffamonkey Alright so in general, annoyingly, this is due to a mismatch in one of your bower angular packages and the exact load order within app.coffee (`client > app > app.coffee`). You're getting this error client side, not during deployment, right?

**Comment by daitoshokan** [comment]
Hi Austin,

Hope you have been well.  I just wanted to let you know I've been getting
these digests today. I'm probably still added to one of your repos... I
know you removed me from Nerdscore but maybe not heroku. I've been on a
trip all day but I can take a look at it from my end when I get home. Just
wanted to let you know I case you don't want me to see any more ASAP.

Good luck,
Charles

**Comment by jaffamonkey** [comment]
@austinkettner Yes, that's correct.  Will try playing with load order and see what happens

**Comment by jaffamonkey** [comment]
@daitoshokan Feels tantalisingly close :)

**Comment by jaffamonkey** [comment]
@austinkettner Here is (first part of) error I get in browser console:
  Uncaught Error: [$injector:modulerr] Failed to instantiate module beepBoopWebsiteApp due to:
Error: [$injector:modulerr] Failed to instantiate module relativeDate due to:
Error: [$injector:nomod] Module 'relativeDate' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=relativeDate
    at https://calm-refuge-6204.herokuapp.com/app/vendor.js:4:982
    at https://calm-refuge-6204.herokuapp.com/app/vendor.js:4:10539
    at b (https://calm-refuge-6204.herokuapp.com/app/vendor.js:4:10012)
    at https://calm-refuge-6204.herokuapp.com/app/vendor.js:4:10324

**Comment by austinkettner** [comment]
Yep those errors are near impossible to pin point, just ensure load order is exact with the bower packages file, as thats how they are inserted into the application during compilation by grunt.

**Comment by austinkettner** [comment]
Is your project open on Github to view? I can debug briefly @jaffamonkey

**Comment by jaffamonkey** [comment]
Here you go @austinkettner  https://github.com/jaffamonkey/angular-blog

**Comment by jaffamonkey** [comment]
I re-forked, and retried. I really had to change very little, which was the remote heroko repo url, the mongo db.  And it worked when running locally, but upon deployment to heroku, the same error on frontend relating to missing module "relativeDate".  This module is installed as part of bower install, and is referenced in app.coffee file and resulting app.js in public folder. So remain baffled :)

**Comment by jaffamonkey** [comment]
Solved :) https://intense-brook-9416.herokuapp.com  I am not entirely sure why it now works, I kept adjusting order of products in bower.json and app.coffee.  Will verify things, then do PR.

**Comment by jaffamonkey** [comment]
There are some quirks with the post edits (some fields ok, some cause post to entirely disappear, or corrupt field (such as choosing cover image).  I feel the content management side has quite a few problems, so may overhaul that.  Closing this issue anyway.
